openapi: 3.0.2
info:
  title: 'Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference'
  version: 'v3'
  description: |
    <div lang="ja">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div>
    <div lang="en">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div>
    <div><a target="_blank" href="https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v3/Route.yaml">OpenAPI Specification</a></div>
    <div lang="ja"><a target="_blank" href="https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja">Best Practice</a></div>
    <div lang="en"><a target="_blank" href="https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en">Best Practice</a></div>

components:
  securitySchemes:
    oAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://biz-oauth.yahoo.co.jp/oauth/v1/authorize
          tokenUrl: https://biz-oauth.yahoo.co.jp/oauth/v1/token
          scopes:
            yahooads: アプリケーションを経由したYahoo!広告の各機能の操作/Operation by each function of Yahoo!
              JAPAN Ads via applications.
security:
  - oAuth: [yahooads]

servers:
  - url: https://ads-search.yahooapis.jp/api/v3

tags:
  - name: AccountManagementService
    description: |
      <label class="account" ></label>
      <div lang="ja">AccountManagementServiceでは、アカウントに関する情報の取得および、追加、更新を行います。</div>
      <div lang="en">AccountManagementService provides functions for creating and managing accounts.</div>
paths:
  /AccountManagementService/get:
    post:
      description: |
        <div lang="ja">アカウントに関する情報を取得します。契約状況などのフィルタ条件を設定することが可能です。</div>
        <div lang="en">Returns the account information. Enable to set the filter condition, such as the account Type.</div>
      tags:
        - AccountManagementService
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'accountmanagement/AccountManagementServiceSelector.yaml#/AccountManagementServiceSelector'
      responses:
        503:
          $ref: '../Response503.yaml#/Response503'
        500:
          $ref: '../Response500.yaml#/Response500'
        200:
          description: |
            <details>
            <summary>Error Codes</summary>
            <table border="1">
            <tr><th>Code</th><th>Message</th><th>Description</th></tr>
            <tr><td>0001</td><td>Invalid Request.</td><td><div lang="ja">さまざまな要因が考えられます。<br>主な要因は、パラメータの値が不正か、誤りがあるためにオペレーションが完了できません。</div><div lang="en">This error can result for a variety of reasons. <br>Typically because one of the parameter values in the request is wrong or invalid and the operation cannot be completed.</div></td></tr>
            <tr><td>R0001</td><td>Require.</td><td><div lang="ja">必須です。</div><div lang="en">It is missing required parameter.</div></td></tr>
            <tr><td>F0001</td><td>Invalid format.</td><td><div lang="ja">値の形式が不正です。</div><div lang="en">The value format is invalid.</div></td></tr>
            <tr><td>V0001</td><td>Invalid value.</td><td><div lang="ja">値が無効です。</div><div lang="en">The value is invalid.</div></td></tr>
            <tr><td>S0001</td><td>Invalid Status.</td><td><div lang="ja">ステータスが無効です。</div><div lang="en">The status is invalid.</div></td></tr>
            <tr><td>L0002</td><td>Over list size.</td><td><div lang="ja">配列の要素数が上限値を超過しています。</div><div lang="en">The number of elements in the array exceeds the upper limit.</div></td></tr>
            <tr><td>L0001</td><td>Lower list size.</td><td><div lang="ja">配列の要素数が下限値を下回っています。</div><div lang="en">The number of elements in the array is below the lower limit.</div></td></tr>
            <tr><td>D0001</td><td>Duplicate.</td><td><div lang="ja">一意な値が重複しています。</div><div lang="en">The unique value is duplicated.</div></td></tr>
            <tr><td>RL001</td><td>Invalid relation.</td><td><div lang="ja">リクエストの関連性が矛盾しています。<br> たとえば、開始＞終了の日付指定を行なっているなど</div><div lang="en">The relation of the request is contradictory.<br> For example, you are specifying the date of start > end.</div></td></tr>
            <tr><td>LT001</td><td>Over limit.</td><td><div lang="ja">登録できる上限値を超過しています。</div><div lang="en">The upper limit value that can be registered is exceeded.</div></td></tr>
            <tr><td>I0001</td><td>Deactivated Id.</td><td><div lang="ja">IDが無効です。</div><div lang="en">The ID is Deactivated.</div></td></tr>
            </table>
            </details>
          content:
            application/json:
              schema:
                $ref: 'accountmanagement/AccountManagementServiceGetResponse.yaml#/AccountManagementServiceGetResponse'
        403:
          $ref: '../Response403.yaml#/Response403'
        401:
          $ref: '../Response401.yaml#/Response401'
        400:
          $ref: '../Response400.yaml#/Response400'
  /AccountManagementService/add:
    post:
      description: |
        <div lang="ja">後請求のアカウントに関する情報を追加します。</div>
        <div lang="en">Adds the information related to the invoice account.</div>
      tags:
        - AccountManagementService
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'accountmanagement/AccountManagementServiceOperation.yaml#/AccountManagementServiceOperation'
      responses:
        503:
          $ref: '../Response503.yaml#/Response503'
        500:
          $ref: '../Response500.yaml#/Response500'
        200:
          description: |
            <details>
            <summary>Error Codes</summary>
            <table border="1">
            <tr><th>Code</th><th>Message</th><th>Description</th></tr>
            <tr><td>0001</td><td>Invalid Request.</td><td><div lang="ja">さまざまな要因が考えられます。<br>主な要因は、パラメータの値が不正か、誤りがあるためにオペレーションが完了できません。</div><div lang="en">This error can result for a variety of reasons. <br>Typically because one of the parameter values in the request is wrong or invalid and the operation cannot be completed.</div></td></tr>
            <tr><td>R0001</td><td>Require.</td><td><div lang="ja">必須です。</div><div lang="en">It is missing required parameter.</div></td></tr>
            <tr><td>F0001</td><td>Invalid format.</td><td><div lang="ja">値の形式が不正です。</div><div lang="en">The value format is invalid.</div></td></tr>
            <tr><td>V0001</td><td>Invalid value.</td><td><div lang="ja">値が無効です。</div><div lang="en">The value is invalid.</div></td></tr>
            <tr><td>S0001</td><td>Invalid Status.</td><td><div lang="ja">ステータスが無効です。</div><div lang="en">The status is invalid.</div></td></tr>
            <tr><td>L0002</td><td>Over list size.</td><td><div lang="ja">配列の要素数が上限値を超過しています。</div><div lang="en">The number of elements in the array exceeds the upper limit.</div></td></tr>
            <tr><td>L0001</td><td>Lower list size.</td><td><div lang="ja">配列の要素数が下限値を下回っています。</div><div lang="en">The number of elements in the array is below the lower limit.</div></td></tr>
            <tr><td>D0001</td><td>Duplicate.</td><td><div lang="ja">一意な値が重複しています。</div><div lang="en">The unique value is duplicated.</div></td></tr>
            <tr><td>RL001</td><td>Invalid relation.</td><td><div lang="ja">リクエストの関連性が矛盾しています。<br> たとえば、開始＞終了の日付指定を行なっているなど</div><div lang="en">The relation of the request is contradictory.<br> For example, you are specifying the date of start > end.</div></td></tr>
            <tr><td>LT001</td><td>Over limit.</td><td><div lang="ja">登録できる上限値を超過しています。</div><div lang="en">The upper limit value that can be registered is exceeded.</div></td></tr>
            <tr><td>I0001</td><td>Deactivated Id.</td><td><div lang="ja">IDが無効です。</div><div lang="en">The ID is Deactivated.</div></td></tr>
            </table>
            </details>
          content:
            application/json:
              schema:
                $ref: 'accountmanagement/AccountManagementServiceMutateResponse.yaml#/AccountManagementServiceMutateResponse'
        403:
          $ref: '../Response403.yaml#/Response403'
        401:
          $ref: '../Response401.yaml#/Response401'
        400:
          $ref: '../Response400.yaml#/Response400'
  /AccountManagementService/set:
    post:
      description: "<div lang=\"ja\">アカウントに関する情報を更新します。</div><div lang=\"en\">Updates\
        \ the information related to the account.</div>"
      tags:
        - AccountManagementService
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'accountmanagement/AccountManagementServiceOperation.yaml#/AccountManagementServiceOperation'
      responses:
        503:
          $ref: '../Response503.yaml#/Response503'
        500:
          $ref: '../Response500.yaml#/Response500'
        200:
          description: |
            <details>
            <summary>Error Codes</summary>
            <table border="1">
            <tr><th>Code</th><th>Message</th><th>Description</th></tr>
            <tr><td>0001</td><td>Invalid Request.</td><td><div lang="ja">さまざまな要因が考えられます。<br>主な要因は、パラメータの値が不正か、誤りがあるためにオペレーションが完了できません。</div><div lang="en">This error can result for a variety of reasons. <br>Typically because one of the parameter values in the request is wrong or invalid and the operation cannot be completed.</div></td></tr>
            <tr><td>R0001</td><td>Require.</td><td><div lang="ja">必須です。</div><div lang="en">It is missing required parameter.</div></td></tr>
            <tr><td>F0001</td><td>Invalid format.</td><td><div lang="ja">値の形式が不正です。</div><div lang="en">The value format is invalid.</div></td></tr>
            <tr><td>V0001</td><td>Invalid value.</td><td><div lang="ja">値が無効です。</div><div lang="en">The value is invalid.</div></td></tr>
            <tr><td>S0001</td><td>Invalid Status.</td><td><div lang="ja">ステータスが無効です。</div><div lang="en">The status is invalid.</div></td></tr>
            <tr><td>L0002</td><td>Over list size.</td><td><div lang="ja">配列の要素数が上限値を超過しています。</div><div lang="en">The number of elements in the array exceeds the upper limit.</div></td></tr>
            <tr><td>L0001</td><td>Lower list size.</td><td><div lang="ja">配列の要素数が下限値を下回っています。</div><div lang="en">The number of elements in the array is below the lower limit.</div></td></tr>
            <tr><td>D0001</td><td>Duplicate.</td><td><div lang="ja">一意な値が重複しています。</div><div lang="en">The unique value is duplicated.</div></td></tr>
            <tr><td>RL001</td><td>Invalid relation.</td><td><div lang="ja">リクエストの関連性が矛盾しています。<br> たとえば、開始＞終了の日付指定を行なっているなど</div><div lang="en">The relation of the request is contradictory.<br> For example, you are specifying the date of start > end.</div></td></tr>
            <tr><td>LT001</td><td>Over limit.</td><td><div lang="ja">登録できる上限値を超過しています。</div><div lang="en">The upper limit value that can be registered is exceeded.</div></td></tr>
            <tr><td>I0001</td><td>Deactivated Id.</td><td><div lang="ja">IDが無効です。</div><div lang="en">The ID is Deactivated.</div></td></tr>
            </table>
            </details>
          content:
            application/json:
              schema:
                $ref: 'accountmanagement/AccountManagementServiceMutateResponse.yaml#/AccountManagementServiceMutateResponse'
        403:
          $ref: '../Response403.yaml#/Response403'
        401:
          $ref: '../Response401.yaml#/Response401'
        400:
          $ref: '../Response400.yaml#/Response400'
